#!/bin/bash
# Run nginx as nginx user on port 8080

pkill nginx || true

sed -i 's/listen 80 default_server;/listen 8080;/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080;/' /etc/nginx/sites-enabled/default

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf

su -s /bin/sh -c "nginx" nginx

ps auxff | grep nginx | grep -v grep
