#!/usr/bin/env bash
# Configures nginx to listen on port 80 and starts the service

sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:8080 default_server;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default

service nginx start

