#!/usr/bin/env bash
# This script configures my Nginx to redirect /redirect_me

apt-get update -y
apt-get install nginx -y

sed -i '/server_name _;/a\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

service nginx restart
