#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me

apt-get update -y
apt-get install -y nginx

sed -i '/server_name _;/a\	location /redirect_me { return 301 https://github.com/lisette-lachiever; }' /etc/nginx/sites-available/default

service nginx restart

